import Foundation

enum DockerCompatibilityTerminalServiceError: LocalizedError, Sendable {
    case appExecutableUnavailable
    case shellUnavailable(String)

    var errorDescription: String? {
        switch self {
        case .appExecutableUnavailable:
            return "无法定位 \(AppBranding.displayName) 可执行文件，不能创建 Docker 兼容终端。"
        case .shellUnavailable(let path):
            return "无法启动 shell：\(path)"
        }
    }
}

struct DockerCompatibilityTerminalEnvironment: Hashable, Sendable {
    var shimBinDirectory: URL
    var shellConfigDirectory: URL
    var shellPath: String
}

struct DockerCompatibilityTerminalService: Sendable {
    func makeSession(
        verboseConversions: Bool = false,
        workingDirectory: URL = AppPaths.homeDirectory
    ) throws -> (session: ContainerTerminalSession, environment: DockerCompatibilityTerminalEnvironment) {
        let environment = try prepareEnvironment()
        let basePath = ProcessInfo.processInfo.environment["PATH"] ?? CommandRunner.defaultSearchRoots().map(\.path).joined(separator: ":")
        let path = "\(environment.shimBinDirectory.path):\(basePath)"
        let overrides: [String: String] = [
            "PATH": path,
            "ZDOTDIR": environment.shellConfigDirectory.path,
            "CONTAINERDESKTOP_DOCKER_SHIM_BIN": environment.shimBinDirectory.path,
            "CONTAINERDESKTOP_DOCKER_SHIM_VERBOSE": verboseConversions ? "1" : "0",
            "TERM": ProcessInfo.processInfo.environment["TERM"] ?? "xterm-256color",
        ]

        let session = ContainerTerminalSession(
            executable: environment.shellPath,
            arguments: ["-i"],
            workingDirectory: workingDirectory,
            environmentOverrides: overrides
        )
        return (session, environment)
    }

    func prepareEnvironment() throws -> DockerCompatibilityTerminalEnvironment {
        let fileManager = FileManager.default
        let shimDirectory = AppPaths.dockerCompatibilityShimBinDirectory
        let shellDirectory = AppPaths.dockerCompatibilityShellDirectory
        try fileManager.createDirectory(at: shimDirectory, withIntermediateDirectories: true)
        try fileManager.createDirectory(at: shellDirectory, withIntermediateDirectories: true)

        let appExecutable = try appExecutablePath()
        try writeShim(named: "docker", appExecutable: appExecutable, to: shimDirectory)
        try writeShim(named: "docker-compose", appExecutable: appExecutable, to: shimDirectory)
        try writeZshConfiguration(shimDirectory: shimDirectory, to: shellDirectory)

        let shellPath = "/bin/zsh"
        guard fileManager.isExecutableFile(atPath: shellPath) else {
            throw DockerCompatibilityTerminalServiceError.shellUnavailable(shellPath)
        }

        return DockerCompatibilityTerminalEnvironment(
            shimBinDirectory: shimDirectory,
            shellConfigDirectory: shellDirectory,
            shellPath: shellPath
        )
    }

    private func appExecutablePath() throws -> String {
        if let bundlePath = Bundle.main.executableURL?.path,
           FileManager.default.isExecutableFile(atPath: bundlePath) {
            return bundlePath
        }

        if let argumentPath = CommandLine.arguments.first,
           FileManager.default.isExecutableFile(atPath: argumentPath) {
            return argumentPath
        }

        throw DockerCompatibilityTerminalServiceError.appExecutableUnavailable
    }

    private func writeShim(named name: String, appExecutable: String, to directory: URL) throws {
        let script = """
        #!/bin/sh
        exec \(ShellEscaper.singleQuoted(appExecutable)) \(DockerCommandShimCLI.argumentFlag) \(ShellEscaper.singleQuoted(name)) "$@"
        """
        let url = directory.appending(path: name)
        try script.write(to: url, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
    }

    private func writeZshConfiguration(shimDirectory: URL, to directory: URL) throws {
        let zshrc = """
        # Generated by \(AppBranding.displayName). This file is rewritten when the Docker compatibility terminal starts.
        export CONTAINERDESKTOP_DOCKER_SHIM_BIN=\(ShellEscaper.singleQuoted(shimDirectory.path))

        if [ -r "$HOME/.zshrc" ] && [ "${CONTAINERDESKTOP_SKIP_USER_ZSHRC:-0}" != "1" ]; then
          source "$HOME/.zshrc"
        fi

        case ":$PATH:" in
          *":$CONTAINERDESKTOP_DOCKER_SHIM_BIN:"*) ;;
          *) export PATH="$CONTAINERDESKTOP_DOCKER_SHIM_BIN:$PATH" ;;
        esac

        export DOCKER_CLI_HINTS=false
        printf '\\033[1;36m%s\\033[0m\\n' "\(AppBranding.displayName) Docker compatibility terminal"
        printf 'docker/docker-compose -> container/container-compose\\n'
        printf 'shim: %s\\n\\n' "$CONTAINERDESKTOP_DOCKER_SHIM_BIN"
        """
        try zshrc.write(to: directory.appending(path: ".zshrc"), atomically: true, encoding: .utf8)
    }
}
