import Foundation

struct DockerCompatibilitySystemTerminalIntegration {
    static let beginMarker = "# >>> ContainerDesktop Docker compatibility >>>"
    static let endMarker = "# <<< ContainerDesktop Docker compatibility <<<"

    var zshrcURL: URL
    var integrationScriptURL: URL
    var backupURL: URL
    var fileManager: FileManager

    init(
        zshrcURL: URL = AppPaths.homeDirectory.appending(path: ".zshrc"),
        integrationScriptURL: URL = AppPaths.dockerCompatibilityShellIntegrationURL,
        backupURL: URL? = nil,
        fileManager: FileManager = .default
    ) {
        self.zshrcURL = zshrcURL
        self.integrationScriptURL = integrationScriptURL
        self.backupURL = backupURL ?? zshrcURL.deletingLastPathComponent().appending(path: ".zshrc.containerdesktop.backup")
        self.fileManager = fileManager
    }

    var isInstalled: Bool {
        guard let text = try? String(contentsOf: zshrcURL, encoding: .utf8) else { return false }
        return text.contains(Self.beginMarker) && text.contains(Self.endMarker)
    }

    func install(shimDirectory: URL) throws {
        try writeIntegrationScript(shimDirectory: shimDirectory)
        if fileManager.fileExists(atPath: zshrcURL.path),
           !fileManager.fileExists(atPath: backupURL.path) {
            try fileManager.copyItem(at: zshrcURL, to: backupURL)
        }

        let existing = (try? String(contentsOf: zshrcURL, encoding: .utf8)) ?? ""
        let cleaned = Self.removingManagedBlock(from: existing).trimmingCharacters(in: .newlines)
        let nextText = [cleaned, sourceBlock]
            .filter { !$0.isEmpty }
            .joined(separator: "\n\n") + "\n"

        try fileManager.createDirectory(at: zshrcURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        try nextText.write(to: zshrcURL, atomically: true, encoding: .utf8)
    }

    func uninstall() throws {
        guard fileManager.fileExists(atPath: zshrcURL.path) else { return }
        let existing = try String(contentsOf: zshrcURL, encoding: .utf8)
        let cleaned = Self.removingManagedBlock(from: existing)
        guard cleaned != existing else { return }
        try cleaned.write(to: zshrcURL, atomically: true, encoding: .utf8)
    }

    func writeIntegrationScript(shimDirectory: URL) throws {
        try fileManager.createDirectory(at: integrationScriptURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        try Self.integrationScript(shimDirectory: shimDirectory)
            .write(to: integrationScriptURL, atomically: true, encoding: .utf8)
        try fileManager.setAttributes([.posixPermissions: 0o644], ofItemAtPath: integrationScriptURL.path)
    }

    var sourceBlock: String {
        """
        \(Self.beginMarker)
        if [ -r \(ShellEscaper.singleQuoted(integrationScriptURL.path)) ]; then
          source \(ShellEscaper.singleQuoted(integrationScriptURL.path))
        fi
        \(Self.endMarker)
        """
    }

    static func integrationScript(shimDirectory: URL) -> String {
        """
        # Generated by \(AppBranding.displayName). This file is safe to source from zsh.
        export CONTAINERDESKTOP_DOCKER_SHIM_BIN=\(ShellEscaper.singleQuoted(shimDirectory.path))
        case ":$PATH:" in
          *":$CONTAINERDESKTOP_DOCKER_SHIM_BIN:"*) ;;
          *) export PATH="$CONTAINERDESKTOP_DOCKER_SHIM_BIN:$PATH" ;;
        esac
        export DOCKER_CLI_HINTS=false
        """
    }

    static func removingManagedBlock(from text: String) -> String {
        guard let begin = text.range(of: beginMarker),
              let end = text.range(of: endMarker, range: begin.upperBound..<text.endIndex)
        else {
            return text
        }

        var result = text
        result.removeSubrange(begin.lowerBound..<end.upperBound)
        while result.contains("\n\n\n") {
            result = result.replacingOccurrences(of: "\n\n\n", with: "\n\n")
        }
        return result.trimmingCharacters(in: .newlines) + (result.trimmingCharacters(in: .newlines).isEmpty ? "" : "\n")
    }
}
